version: '3.8'
services: 
    api-service:
        build: ./app/
        volumes: 
            - ./app/:/app/
        ports: 
            - 5000:5000
        environment:
            PORT: 5000
            FLASK_ENV: development
            FLASK_DEBUG: 1
