version: '3.8'

services:
            
    api-service:
        container_name: pytest
        command: pytest
        environment:
            FLASK_ENV: development
            FLASK_DEBUG: 1
            MONGODB_DATABASE: test_cache
