version: '3.8'

services:

    api-service:
        build: ./app/
        container_name: flask
        command: python api.py
        volumes:
            - './app/:/app/'
        environment:
            PORT: 5000
            MONGODB_DATABASE: cache
            MONGODB_HOSTNAME: mongodb
            MONGODB_PORT: 27017
            LATEST_WEATHERS_DEFAULT_MAX: 5
            CACHED_WEATHERS_EXPIRATION_TIME: 300
            OPEN_WEATHER_ENDPOINT:
                http://api.openweathermap.org/data/2.5/weather
            OPEN_WEATHER_API_KEY: 09d9c578d13c2303e83f7b7f94f12d3f
        networks:
            - backend

    db-service:
        image: mongo
        container_name: mongodb
        volumes:
            - 'mongodbdata:/data/db'
        environment:
            PORT: 27017
            MONGO_INITDB_DATABASE: cache
            MONGODB_DATA_DIR: /data/db
            MONDODB_LOG_DIR: /dev/null
        networks:
            - backend

networks:
    backend:
        driver: bridge
volumes:
    mongodbdata:
        driver: local
