version: '3.8'

services:

    api-service:
        build: ./app/
        container_name: flask
        command: python api.py
        volumes:
            - './app/:/app/'
        ports:
            - '5000:5000'
        environment:
            PORT: 5000
            MONGODB_DATABASE: cache
            MONGODB_HOSTNAME: mongodb
        depends_on:
            - db-service
        networks:
            - backend

    db-service:
        image: mongo
        container_name: mongodb
        volumes:
            - 'mongodbdata:/data/db'
        environment:
            MONGO_INITDB_DATABASE: cache
            MONGODB_DATA_DIR: /data/db
            MONDODB_LOG_DIR: /dev/null
        networks:
            - backend

networks:
    backend:
        driver: bridge
volumes:
    mongodbdata:
        driver: local
